name: Workflow for Appium
run-name: Workflow for Appium

on: [push]

jobs:
  mobile-tests:
    runs-on: ubuntu-latest   # Run on free Linux runners instead of macOS

    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: appium-test-report
          path: tests/appium/*.xlsx
